title: Isaac Macpherson Jaynes # your name (or website title) here
logo: "/images/profile_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BSc Mathematics from The University of British Columbia Vancouver 
  <br><br>
  Intermediate Software Engineer at <a href="https://cpl.thalesgroup.com/">Thales CPL</a> (formerly <a href="https://www.imperva.com/">Imperva</a>)
  <br><br>
  <a href="https://www.linkedin.com/in/isaac-m-jaynes/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-QM8JNMDMNX # your Google Analytics tracking ID here
